apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkinsx-test-dev-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: jenkinsx-test-dev
spec:
  backend:
    serviceName: jenkinsx-test-dev
    servicePort: 8080