apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkinsx-test-prod
  labels:
    app: jenkinsx-test-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkinsx-test-prod
  template:
    metadata:
      labels:
        app: jenkinsx-test-prod
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1"
        image: docker.io/randymay/jenkinsx-test:0.0.2-SNAPSHOT
        imagePullPolicy: Always
        name: jenkinsx-test-prod
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "4096Mi"
          limits:
            memory: "4096Mi"
      restartPolicy: Always